### ISSUE TITLE
Webinar Question

### ISSUE THREAD

**Issue by lmcdon14** [COSCS340/news#8]
Dr. Mockus, 

A number of times during your presentation in the ACM Webinar, you allude to the discrepancy between how project managers and actual developers view risky files and customer-found defects. Specifically, you mention that managers tend to only look at the overall larger picture of the problem while developers are able to pinpoint the issues in specific files. Do you believe that it would be beneficial for management-level employees to have a stronger programming background (or at least direct access to risky file analysis tools such as you presented) in order to also have the ability to track down individual defects in code development? What other ways can the relationships between management and developers be improved in order to more effectively diminish the consequences associated with risky files?

**Comment by audrism** [comment]
Good question Landon 

There are a couple of aspects to the answer. While many of lower-level managers tend to 
be former developers of the same products, the approach is more suitable to cases where
product was acquired or outsourced: where the new managers do not have first-hand experience
developing the product. 
Second, in many organizations the funding is provided by higher-level manages who rarely
have development expertise in general or specific product expertise in particular.

The purpose of the toll is, as you point out, to align priorities  and providing access to managers 
and incorporating it into the company's quality framework is the main objective.

The question of how to better align management and developer priorities is really important. 
RFM is but one of may approaches that could be taken, but I do not believe that in industry it is 
perceived as a serious problem that needs to be addressed or does not get sufficient attention.
